pattern_annotator_local/main/urls.py
from django.urls import path
from . import views
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views

app_name = 'main'
urlpatterns = [
    path('', views.index, name="index"),
    path('register', views.register, name="register"),
    path('logout', views.logout_request, name="logout"),
    path('login', views.login_request, name="login"),
    url(r'^ajax/get_filenames/$', views.get_filenames, name='get_filenames'),
    url(r'^ajax/get_result_filenames/$', views.get_result_filenames, name='get_result_filenames'),
    url(r'^ajax/post_xml_patterns/$', views.post_xml_patterns, name='post_xml_patterns'),
    url(r'^ajax/post_user_behaviour/$', views.post_user_behaviour, name='post_user_behaviour'),
    url(r'^ajax/update_user_song_list/$', views.update_user_song_list, name='update_user_song_list'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.activate, name='activate'),
    url(r'password_reset/$', views.mypassword_reset_view, name='password_reset'),
    #url(r'password_reset/$',auth_views.PasswordResetView.as_view(template_name='custom_menus/password_reset_form.html',email_template_name='custom_menus/password_reset_email.html',subject_template_name='custom_menus/password_reset_subject.txt',success_url='/password_reset/done/'), name='password_reset'),
    url(r'^password_reset/done/$', auth_views.PasswordResetDoneView.as_view(template_name="custom_menus/password_reset_done.html"), name='password_reset_done'),
    #url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', auth_views.PasswordResetConfirmView.as_view(template_name="custom_menus/password_reset_confirm.html", success_url='/reset/done/'), name='password_reset_confirm'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', auth_views.PasswordResetConfirmView.as_view(template_name="custom_menus/password_reset_confirm.html", success_url='/login'), name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.PasswordResetCompleteView.as_view(template_name="custom_menus/password_reset_complete.html"), name='password_reset_complete'),
]

pattern_annotator_local/main/models.py
from django.db import models
from datetime import datetime
from django.contrib.auth.models import User
from jsonfield import JSONField

# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    age = models.PositiveIntegerField(null=True)
    instrument = models.CharField(max_length=200, null=True)
    instrument_years = models.PositiveIntegerField(null=True)
    theory_years = models.PositiveIntegerField(null=True)
    country = models.CharField(max_length=200,null=True)
    university = models.CharField(max_length=200, null=True)
    programme = models.CharField(max_length=200,null=True)
    year_of_study = models.CharField(max_length=200, null=True, default=None)
    song_list = JSONField(default=list)


    def __str__(self):
        return "{}: {}, {}".format(self.user.username, self.instrument, self.age)
        
class Pattern(models.Model):
    #pattern_id = models.AutoField(primary_key=True, default=0)
    user_id = models.IntegerField(null=True)
    song_id = models.IntegerField(null=True)
    xml_file = models.TextField(null=True) # blob of text
    pattern_rank = models.IntegerField(null=True)
    pattern_timestamp = models.IntegerField(null=True)
    pattern_tag = models.CharField(max_length=150, null=True)
    is_automatic = models.BooleanField(null=True)
    # override string method, when printed with string
    def __str__(self):
        return "Pattern({}): user({}) on song({}), with rank({}) and tag[{}]".format(self.id, self.user_id, self.song_id, self.pattern_rank, self.pattern_tag)

class UserBehaviour(models.Model):
    user_id = models.IntegerField(null=True)
    song_id = models.IntegerField(null=True)
    midi_start_times = JSONField(default=list)
    midi_stop_times = JSONField(default=list)
    number_of_annotations = models.IntegerField(null=True)
    number_of_deletions = models.IntegerField(null=True)
    
    # override string method, when printed with string
    def __str__(self):
        return "Behaviour of User({}) on Song({})".format(self.user_id, self.song_id)
        

pattern_annotator_local/main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Profile
from django.contrib.auth.forms import AuthenticationForm
from django.forms.widgets import PasswordInput, TextInput

class NewUserForm(UserCreationForm):
    email = forms.EmailField(required=True)
    
    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def save(self, commit=True):
        user = super(NewUserForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        #user.age = self.cleaned_data['age']
        if (commit):
            user.save()
        return user

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('age','instrument','instrument_years','theory_years',
                  'country', 'university', 'programme', 'year_of_study')

class PasswordResetForm(forms.ModelForm):
    email = forms.EmailField(required=True)

pattern_annotator_local/main/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Pattern, Profile, UserBehaviour
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout, authenticate
from django.contrib import messages
from .forms import NewUserForm, ProfileForm
from django.contrib.auth.decorators import login_required, user_passes_test
from django.http import JsonResponse
from django.contrib.staticfiles.templatetags.staticfiles import static
import os 
from django.conf import settings
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes, force_text
from .tokens import account_activation_token
from django.core.mail import EmailMessage
from django.contrib.auth.models import User
from django.contrib.auth.views import PasswordResetView, PasswordContextMixin

from django.contrib.auth.forms import PasswordResetForm
from django.urls import reverse_lazy
from django.contrib.auth.tokens import default_token_generator
from django.views.generic.edit import FormView
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_protect

import random
import json

def is_registered(user):
    return user.is_authenticated

def is_not_logged_in(user):
    return user.is_anonymous

# Create your views here.
@login_required(login_url='/login')
#@user_passes_test(is_registered)
def index(request):
    context = {}
    list_of_songs = get_song_names(request)
    song_names = []

    for song in list_of_songs:
        tmp = song.split('.')[0]
        tmp = tmp.split('_')[1:]
        tmp = " ".join(tmp)
        song_names.append(tmp)

    
    context['list_of_songs'] = list_of_songs
    context['song_names'] = song_names
    return render(request=request, 
                  template_name="index.html", context=context)

@login_required(login_url='/login')
def update_user_song_list(request):
    current_user = request.user
    
    song_list = current_user.profile.song_list
    #song_names = request.session.get('song_names')
    #print(song_names)
    #print(current_user)
    #print(song_list)
    #print("updating yo")
    data = {
        'code': "200",
        'user': current_user.id,
        'song_list': song_list,
        'song_names': None,
    }
    return JsonResponse(data)

# REGISTER
@user_passes_test(is_not_logged_in, login_url='main:index')
def register(request):
    if (request.method == "POST"):
        form = NewUserForm(request.POST)
        profile_form = ProfileForm(request.POST)

        if ( form.is_valid() and profile_form.is_valid() ):
            #print("we are here")
            # save user from form

            user = form.save(commit=False)
            user.is_active = False
            user.save()
            #username = form.cleaned_data.get('username')
            # save profile from form
            for field in profile_form.changed_data:
                setattr(user.profile, field, profile_form.cleaned_data.get(field))
            #user.profile.instrument = profile_form.cleaned_data.get('instrument')
            #user.profile.age = profile_form.cleaned_data.get('age')
            user.profile.save()  

            # SEND EMAIL
            current_site = get_current_site(request)
            #temporary_domain = "mydomain.com"
            mail_subject = 'Activate your Pattern Annotator account.'
            message = render_to_string('acc_active_email.html', {
                                    'user': user,
                                    'domain': current_site,#current_site.domain,
                                    'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                                    'token': account_activation_token.make_token(user),
            })
            to_email = form.cleaned_data.get('email')
            email = EmailMessage(
                mail_subject, message, to=[to_email]
            )
            email.send()
            messages.info(request, "A confirmation link was sent to the provided email adress.")
            messages.info(request, "Please check your inbox to complete the registration process.")

            #messages.info(request, "Please confirm your email address to complete the registration")
            # message user and login
            #messages.success(request, f"New Account Created: {username}")
            #login(request, user)
            #messages.info(request, f"You are now logged in as {username}")
            #return redirect("main:index")
            
        else:
            for field, errors in sorted(form.errors.items(), reverse=True):
                #print("field")
                for error in errors:
                    #print("error:")
                    #print(error)
                    #messages.error(request, form.fields[field].label + ": " + error )
                    messages.error(request, error)
    else:
        form = NewUserForm()
        profile_form = ProfileForm()
    return render(request,
                  "register.html",
                  context={"form":form, 'profile_form':profile_form})


@user_passes_test(is_not_logged_in, login_url='main:index')
def password_reset(request):
    if (request.method == "POST"):
        form = PasswordResetForm(request.POST)
        profile_form = ProfileForm(request.POST)

        if ( form.is_valid() and profile_form.is_valid() ):
            #print("we are here")
            # save user from form

            user = form.save(commit=False)
            user.is_active = False
            user.save()
            #username = form.cleaned_data.get('username')
            # save profile from form
            for field in profile_form.changed_data:
                setattr(user.profile, field, profile_form.cleaned_data.get(field))
            #user.profile.instrument = profile_form.cleaned_data.get('instrument')
            #user.profile.age = profile_form.cleaned_data.get('age')
            user.profile.save()  

            # SEND EMAIL
            current_site = get_current_site(request)
            #temporary_domain = "mydomain.com"
            mail_subject = 'Activate your Pattern Annotator account.'
            message = render_to_string('acc_active_email.html', {
                                    'user': user,
                                    'domain': current_site,#current_site.domain,
                                    'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                                    'token': account_activation_token.make_token(user),
            })
            to_email = form.cleaned_data.get('email')
            email = EmailMessage(
                mail_subject, message, to=[to_email]
            )
            email.send()
            messages.info(request, "A confirmation link was sent to the provided email adress.")
            messages.info(request, "Please check your inbox to complete the registration process.")

            #messages.info(request, "Please confirm your email address to complete the registration")
            # message user and login
            #messages.success(request, f"New Account Created: {username}")
            #login(request, user)
            #messages.info(request, f"You are now logged in as {username}")
            #return redirect("main:index")
            
        else:
            for field, errors in sorted(form.errors.items(), reverse=True):
                #print("field")
                for error in errors:
                    #print("error:")
                    #print(error)
                    #messages.error(request, form.fields[field].label + ": " + error )
                    messages.error(request, error)
    else:
        form = NewUserForm()
        profile_form = ProfileForm()
    return render(request,
                  "register.html",
                  context={"form":form, 'profile_form':profile_form})

# LOGOUT
def logout_request(request):
    logout(request)
    messages.info(request, "Logged out successfully!")
    return redirect("main:login")




# LOGIN
@user_passes_test(is_not_logged_in, login_url='main:index')
def login_request(request):
    if (request.method == "POST"):
        form = AuthenticationForm(request, data=request.POST)
        if (form.is_valid()):

            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)

            if (user is not None):
                login(request, user)
                messages.info(request, "You are now logged in as {}.".format(username)) #f"You are now logged in as {username}")
                return redirect("main:index")
        else:
            messages.error(request, "Invalid username or password.")


    form = AuthenticationForm()
    return render(request, 
                  "login.html",
                  {"form": form})

# GET MEI FILENAMES
@login_required(login_url='/login')
def get_filenames(request):
    song_names = get_song_names(request)
    data = {
        'file_list': song_names
    }

    return JsonResponse(data)

@login_required(login_url='/login')
def get_song_names(request):
    app_path = os.path.dirname(os.path.abspath(__file__))
    static_path = static('mei/')
    path = app_path + static_path
    song_names = os.listdir(path)
    song_names.sort()
    random.seed(request.user.id)
    random.shuffle(song_names)
    return song_names


# GET RESULT FILENAMES
@login_required(login_url='/login')
def get_result_filenames(request):
    app_path = os.path.dirname(os.path.abspath(__file__))
    static_path = static('result/')
    path = app_path + static_path
    song_names = os.listdir(path)
    data = {
        'file_list': song_names
    }
    return JsonResponse(data)

# POST XML

pattern_annotator_local/main/templates/includes/messages.html
{% if messages %}
    {% for message in messages %}
        {% if message.tags == 'success'%}
            <script>M.toast({html: "{{message}}", classes: 'green', displayLength:5000});</script>
        {% elif message.tags == 'info'%}
            <script>M.toast({html: "{{message}}", classes: 'blue', displayLength:5000});</script>
        {% elif message.tags == 'warning'%}
            <script>M.toast({html: "{{message}}", classes: 'orange', displayLength:5000});</script>
        {% elif message.tags == 'error'%}
            <script>M.toast({html: "{{message}}", classes: 'red', displayLength:5000});</script>
        {% endif %}
    {% endfor %}
{% endif %}

pattern_annotator_local/main/templates/includes/modal.html
<!-- The Modal -->
<div id="overlay_instructions" class="modal">
        
    <!-- Modal content -->
    <div class="modal_content_custom_no">
        <div class="modal-header_custom">
            <span class="close modal-close">&times;</span>
            <p>Welcome to the Pattern Annotator</p>
        </div>
        <div class="modal-body_custom">
            <p>The goal of the site is to allow users to find and submit patterns found in music.</p>
            <br>
            <p>A musical pattern or motive is defined as a short musical idea, a salient recurring figure,
                musical fragment, or succession of notes that has some special
                importance in or is characteristic of a composition. It
                shouldn’t be longer than a musical phrase. If you find a
                motive that is similar to another (or multiple versions of a
                motive), choose the one that you think is the most
                representative.
            </p>
            <br>
            <p>To begin, click on a note to mark it as the start of a pattern. The starting note will be coloured <span style="color:blue;">blue</span>. 
                Next, click on another note to mark the end of that pattern.
                All of the notes between the start and the end will be coloured  <span style="color:red;">red</span>, thus representing a marked pattern.
                To mark multiple patterns simply repeat the process.
                Once a pattern is finalised you can rate it from 1 (not as relevant) to 3 (highly relevant). 

            </p>
            <br>
            <p>To delete an UNFINISHED pattern click on its starting note, which is coloured blue. 
            </p>
            <p>To delete an already FINISHED pattern press on the X button, which can be found in the right corner of each pattern.
            </p>
            <br>
            <p> To navigate the sheet music use the buttons located below the sheet music.
                You can also use the arrow keys on your keyboard to achieve the same result.

                Once you are finished click on the SUBMIT PATTERNS button and click OK. The patterns will then be submitted and the site will take you to your next task.
            </p>
            <br>
            
            <p>To zoom out or in press - or +.</p>
            <p>To use the music player simply click on the play button. You can also navigate the song by clicking on the song progress bar in the top left.</p>

        </div>
    </div>

</div>
<script>
    $(document).ready(function() {
        $('#overlay_instructions').modal({startingTop: '10%', endingTop: '16%',});
    });
</script>

pattern_annotator_local/main/templates/includes/navbar.html
{% url 'main:index' as index %}
{% url 'main:login' as login %}
{% url 'main:register' as register %}
{% url 'main:password_reset' as password_reset %}
<!-- Dropdown Structure -->
<ul id='dropdown1' class='dropdown-content'>
    <li><a href="/logout">Logout</a></li>
</ul>
<ul class="sidenav" id="mobile-demo">
    {% if user.is_authenticated %}
        <li><a onclick="open_song_menu()">Select song</a></li>
        <li><a onclick="open_instructions()" class="sidenav-close" >Instructions</a></li>
        <li><a href="/logout">Logout</a></li>   
    
    {% else %}
        <li><a onclick="open_instructions()">About</a></li>          
        {% if request.path == login %}
            <li><a href="/password_reset">Forgot password?</a></li>
            <li><a href="/register">Register</a></li>
        {% elif request.path == register %}
            <li><a href="/password_reset">Forgot password?</a></li>
            <li><a href="/login">Login</a></li>
        {% elif request.path == password_reset %}
            <li><a href="/register">Register</a></li>
            <li><a href="/login">Login</a></li>
        {% else %}
            <li><a href="/password_reset">Forgot password?</a></li>
            <li><a href="/register">Register</a></li>
            <li><a href="/login">Login</a></li>         
        {% endif %}
    {% endif %}
</ul>

<nav class="navbar" id="navbar">
    <div class="nav-wrapper" id="nav-wrapper">
        <a href="#" class="brand-logo" style="margin-left:20px; margin-right:20px">Pattern Annotator</a>
        <a href="#" data-target="mobile-demo" class="sidenav-trigger right"><i class="material-icons">menu</i></a>
        <ul id="nav-mobile" class="right hide-on-med-and-down"> 
            {% if user.is_authenticated %}
                <li><a onclick="open_song_menu()">Select song</a></li>
                <li><a onclick="open_instructions()">Instructions</a></li>
                <!-- Dropdown Trigger -->
                <li><a class='dropdown-trigger' id="user_dropdown" href='#' data-target='dropdown1'>{{user.username}} <i class="fa fa-caret-down"></i></a></li>
                
            {% else %}
                <li><a onclick="open_instructions()">About</a></li>
                
                {% if request.path == login %}
                    <li><a href="/password_reset">Forgot password?</a></li>
                    <li><a href="/register">Register</a></li>

                {% elif request.path == register %}
                    <li><a href="/password_reset">Forgot password?</a></li>
                    <li><a href="/login">Login</a></li>

                {% elif request.path == password_reset %}

                    <li><a href="/register">Register</a></li>
                    <li><a href="/login">Login</a></li>
                {% else %}
                    <li><a href="/password_reset">Forgot password?</a></li>
                    <li><a href="/register">Register</a></li>
                    <li><a href="/login">Login</a></li>
                    
                {% endif %}
                
            {% endif %}
        </ul>
    </div>
</nav>
<script>
    $('.sidenav').sidenav({
        "edge": "right",
    });

    $(".dropdown-trigger").dropdown({
        "constrain_width": true, 
        "coverTrigger": false,
        "alignment": "top",
    });
    
    function open_instructions(){
        $('#overlay_instructions').modal('open');
    }
    function open_song_menu(){
        show_song_menu();
    }
</script>
    

pattern_annotator_local/main/templates/includes/song_menu.html
<!-- The Modal -->
<div id="overlay_song_menu" class="modal">
        
    <!-- Modal content -->
    <div class="modal_content_custom_no">
        <div class="modal-header_custom">
            <span class="close modal-close">&times;</span>
            <p>Pick a song to annotate</p>
        </div>
        <div class="modal-body_song_menu">
            <p>
                {#{ request.user.profile.song_list }#}
                {% for song in song_names %}
                    {#% if forloop.counter in request.user.profile.song_list %#}
                        <!--button class="btn_pick_song_done" id="btn_pick_song_done">{{ forloop.counter }}</button-->
                    {#% else %#}
                    <!--button class="btn_pick_song_not_done" id="btn_pick_song_not_done" onclick="close_song_menu();no_submit_load_next('{{ forloop.counter0 }}'); ">{{ forloop.counter }}</button-->
                    <button class="btn_pick_song_not_done" id="btn_pick_song_not_done" song_id="{{forloop.counter}}" onclick="close_song_menu();no_submit_load_next('{{ forloop.counter0 }}'); ">{{ song }}</button>
                    
                    {#% endif %#}
                {% endfor %}
            </p>
        </div>
    </div>

</div>
<script>
    $(document).ready(function() {
        $('#overlay_song_menu').modal({startingTop: '10%', endingTop: '16%',});
    });
    
</script>