pattern_annotator/main/urls.py
from django.urls import path
from . import views
from django.conf.urls import url

app_name = 'main'
urlpatterns = [
    path('', views.index, name="index"),
    path('register', views.register, name="register"),
    path('logout', views.logout_request, name="logout"),
    path('login', views.login_request, name="login"),
    url(r'^ajax/get_filenames/$', views.get_filenames, name='get_filenames'),
    url(r'^ajax/get_result_filenames/$', views.get_result_filenames, name='get_result_filenames'),
    url(r'^ajax/post_xml_patterns/$', views.post_xml_patterns, name='post_xml_patterns'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.activate, name='activate'),
]

pattern_annotator/pattern_annotator/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
]

pattern_annotator/main/models.py
from django.db import models
from datetime import datetime
from django.contrib.auth.models import User

# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    age = models.PositiveIntegerField(null=True)
    instrument = models.CharField(max_length=200)
    instrument_years = models.PositiveIntegerField(null=True)
    theory_years = models.PositiveIntegerField(null=True)
    country = models.CharField(max_length=200,)
    university = models.CharField(max_length=200)
    programme = models.CharField(max_length=200)
    
    def __str__(self):
        return "{}: {}, {}".format(self.user.username, self.instrument, self.age)
        #return f'{self.user.username}: {self.instrument}, {self.age}'

class Pattern(models.Model):
    #pattern_id = models.AutoField(primary_key=True, default=0)
    user_id = models.IntegerField(null=True)
    song_id = models.IntegerField(null=True)
    xml_file = models.TextField(null=True) # blob of text
    pattern_rank = models.IntegerField(null=True)
    pattern_timestamp = models.IntegerField(null=True)
    
    # override string method, when printed with string
    def __str__(self):
        return "Pattern({}): user({}) on song({}), with rank({})".format(self.id, self.user_id, self.song_id, self.pattern_rank)
        #return f'Pattern({self.id}): user({self.user_id}) on song({self.song_id}), with rank({self.pattern_rank})'

pattern_annotator/main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Profile
from django.contrib.auth.forms import AuthenticationForm
from django.forms.widgets import PasswordInput, TextInput

class NewUserForm(UserCreationForm):
    email = forms.EmailField(required=True)
    
    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def save(self, commit=True):
        user = super(NewUserForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        #user.age = self.cleaned_data['age']
        if (commit):
            user.save()
        return user

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('age','instrument','instrument_years','theory_years',
                  'country', 'university', 'programme' )

pattern_annotator/main/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Pattern
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout, authenticate
from django.contrib import messages
from .forms import NewUserForm, ProfileForm
from django.contrib.auth.decorators import login_required, user_passes_test
from django.http import JsonResponse
from django.contrib.staticfiles.templatetags.staticfiles import static
import os 
from django.conf import settings
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes, force_text
from .tokens import account_activation_token
from django.core.mail import EmailMessage
from django.contrib.auth.models import User

def is_registered(user):
    return user.is_authenticated

def is_not_logged_in(user):
    return user.is_anonymous
    
# Create your views here.
@login_required(login_url='/login')
#@user_passes_test(is_registered)
def index(request):
    return render(request=request, 
                  template_name="index.html")

# REGISTER
@user_passes_test(is_not_logged_in, login_url='main:index')
def register(request):
    if (request.method == "POST"):
        form = NewUserForm(request.POST)
        profile_form = ProfileForm(request.POST)

        if ( form.is_valid() and profile_form.is_valid() ):
            #print("we are here")
            # save user from form

            user = form.save(commit=False)
            user.is_active = False
            user.save()
            #username = form.cleaned_data.get('username')
            # save profile from form
            for field in profile_form.changed_data:
                setattr(user.profile, field, profile_form.cleaned_data.get(field))
            #user.profile.instrument = profile_form.cleaned_data.get('instrument')
            #user.profile.age = profile_form.cleaned_data.get('age')
            user.profile.save()  

            # SEND EMAIL
            current_site = get_current_site(request)
            #temporary_domain = "mydomain.com"
            mail_subject = 'Activate your Pattern Annotator account.'
            message = render_to_string('acc_active_email.html', {
                                    'user': user,
                                    'domain': current_site,#current_site.domain,
                                    'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                                    'token': account_activation_token.make_token(user),
            })
            to_email = form.cleaned_data.get('email')
            email = EmailMessage(
                mail_subject, message, to=[to_email]
            )
            email.send()
            messages.info(request, "A confirmation link was sent to the provided email adress.")
            messages.info(request, "Please check your inbox to complete the registration process.")

            #messages.info(request, "Please confirm your email address to complete the registration")
            # message user and login
            #messages.success(request, f"New Account Created: {username}")
            #login(request, user)
            #messages.info(request, f"You are now logged in as {username}")
            #return redirect("main:index")
            
        else:
            for field, errors in sorted(form.errors.items(), reverse=True):
                #print("field")
                for error in errors:
                    #print("error:")
                    #print(error)
                    #messages.error(request, form.fields[field].label + ": " + error )
                    messages.error(request, error)
    else:
        form = NewUserForm()
        profile_form = ProfileForm()
    return render(request,
                  "register.html",
                  context={"form":form, 'profile_form':profile_form})


# LOGOUT
def logout_request(request):
    logout(request)
    messages.info(request, "Logged out successfully!")
    return redirect("main:login")

# LOGIN
@user_passes_test(is_not_logged_in, login_url='main:index')
def login_request(request):
    if (request.method == "POST"):
        form = AuthenticationForm(request, data=request.POST)
        if (form.is_valid()):

            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)

            if (user is not None):
                login(request, user)
                messages.info(request, "You are now logged in as {}.".format(username)) #f"You are now logged in as {username}")
                return redirect("main:index")
        else:
            messages.error(request, "Invalid username or password.")


    form = AuthenticationForm()
    return render(request, 
                  "login.html",
                  {"form": form})

# GET MEI FILENAMES
@login_required(login_url='/login')
def get_filenames(request):

    app_path = os.path.dirname(os.path.abspath(__file__))
    static_path = static('mei/')
    path = app_path + static_path
    song_names = os.listdir(path)
    song_names.sort()
    data = {
        'file_list': song_names
    }
    return JsonResponse(data)

# GET RESULT FILENAMES
@login_required(login_url='/login')
def get_result_filenames(request):

    app_path = os.path.dirname(os.path.abspath(__file__))
    static_path = static('result/')
    path = app_path + static_path
    song_names = os.listdir(path)
    data = {
        'file_list': song_names
    }
    return JsonResponse(data)

# POST XML
@login_required(login_url='/login')
def post_xml_patterns(request):
    
    current_user = request.user
    user_id = current_user.id
    which_song = request.POST.get('which_song', None)
    xml_string_pattern = request.POST.get('xml_string_pattern', None)
    pattern_rank = request.POST.get('pattern_rank', None)
    pattern_timestamp = request.POST.get('pattern_timestamp', None)
    print()
    print("user id is: ", user_id)
    print("song id is: ", which_song)
    print(xml_string_pattern)
    print()
    pat = Pattern(user_id=user_id, song_id=which_song, xml_file=xml_string_pattern, pattern_rank=pattern_rank, pattern_timestamp=pattern_timestamp)
    pat.save()

    data = {
        'code': "200",
        'user': user_id,
        'which_song': which_song
    }
    return JsonResponse(data)

# email verification
@user_passes_test(is_not_logged_in, login_url='main:index')
def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user)
        messages.info(request, "Thank you for your email confirmation.")#f"Thank you for your email confirmation")
        messages.info(request, "You are now logged in as {}.".format(user.username))
        return redirect('main:index')
        # return HttpResponse('Thank you for your email confirmation. Now you can login your account.')
    else:
        return HttpResponse('Activation link is invalid!')

pattern_annotator/main/templates/acc_active_email.html
{% autoescape off %}
    Hi {{ user.username }},
    Please click on the link to confirm your registration,
    http://{{ domain }}{% url 'main:activate' uidb64=uid token=token %}
{% endautoescape %}

pattern_annotator/main/templates/header.html
{% load static %}
<head>
    <title>Pattern Annotator</title>
    <!-- PREVIOUS CSS HERE -->
    <!-- RESET STYLESHEET-->
    <link rel="stylesheet" href="{% static 'css/reset.css'%}" title="external style sheet">
    
    <!-- We also use jQuery -->
    <!--script src="https://code.jquery.com/jquery-3.1.1.min.js" type="text/javascript" ></script--> 
    <script src="{% static 'js/jquery-3.1.1.js' %}" type="text/javascript" ></script>
    <!-- MATERIALIZE -->
    <!-- Compiled and minified CSS -->
    <!--link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css"-->
    <link rel="stylesheet" href="{% static 'materialize/css/materialize.css' %}" title="external style sheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!-- Compiled and minified JavaScript -->
    <!--script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script-->
    

    <!-- HEADER CSS -->
    <link rel="stylesheet" href="{% static 'css/header_style.css' %}">
    <!--link rel="stylesheet" href="{% static 'css/register_style.css' %}"-->

    <!-- Favicon -->
    <link rel="icon" href="#">
    <link rel="shortcut icon" type="image/png" href="{% static 'img/favicon.png' %}"/>

    <!-- ADD GENERAL STYLES -->
    <link rel="stylesheet" href="{% static 'css/general_style.css' %}" title="external style sheet">
    
    
    <!-- LOADING SCREEN STYLE -->
    <link rel="stylesheet" href="{% static 'css/style_loader.css' %}" title="external style sheet">

    <!--FA icons -->
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
    <!-- MODAL -->
    <link rel="stylesheet" href="{% static 'css/modal.css' %}" title="external style sheet">
    <!-- CSS -->
    {% block css %}
    {% endblock %}
    <!-- JAVASCRIPT -->
    {% block scripts %}
    {% endblock %}
</head>
<body>
    <script src="{% static 'materialize/js/materialize.js' %}" type="text/javascript"></script>
    {% include "includes/navbar.html" %}
    {% include "includes/messages.html" %}
    {% include "includes/modal.html" %}
    
    <script src="{% static 'js/instructions_button.js' %}"  type="text/javascript"></script>
    {% block content %}
    {% endblock %}
    
</body>

pattern_annotator/main/templates/index.html
{% extends "header.html" %}
{% load static %}
    
{% block css %}
    <!-- add styles in seperate file, from css folder-->
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" title="external style sheet">
    <!--link rel="stylesheet" href="{% static 'css/modal.css' %}" title="external style sheet"-->

    <!-- MIDIPLAYER STYLESHEET -->
    <link rel="stylesheet" href="{% static 'css/midiplayer.css' %}" title="external style sheet" />
{% endblock %}
{% block scripts %}
    <!-- JAVASCRIPT -->
    <!--/////////////////////--> 
    <!-- The Verovio toolkit -->   
    <script src="https://www.verovio.org/javascript/develop/verovio-toolkit.js" type="text/javascript" ></script>
    <!-- We also use jQuery -->
    <!--script src="https://code.jquery.com/jquery-3.1.1.min.js" type="text/javascript" ></script-->
    <script src="{% static 'js/jquery-3.1.1.js' %}" type="text/javascript" ></script>
    <!-- Basic events from example 02 -->
    <script src="{% static 'js/basic-events.js' %}" type="text/javascript" ></script>
    <!--/////////////-->
    <!-- MIDI Player -->
    <!--/////////////-->
    <script type="text/javascript" language="javascript" src="{% static 'js/midi-player/wildwebmidi.js' %}"></script>
    <script type="text/javascript" language="javascript" src="{% static 'js/midi-player/midiplayer.js' %}"></script>
    <script type="text/javascript" language="javascript" src="{% static 'js/output_xml.js' %}"></script>
    <script type="text/javascript" language="javascript" src="{% static 'js/svg_rect.js' %}"></script>
    <!-- TRUE MIDI PLAYER COMPONENTS-->
    <!-- shim -->
    <script src="{% static 'js/midi_player_scripts/inc/shim/Base64.js'       %}" type="text/javascript"></script>
    <script src="{% static 'js/midi_player_scripts/inc/shim/Base64binary.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/midi_player_scripts/inc/shim/WebAudioAPI.js'  %}" type="text/javascript"></script>
    <script src="{% static 'js/midi_player_scripts/inc/shim/WebMIDIAPI.js'   %}" type="text/javascript"></script>
    <!-- jasmid pmidikage -->
    <script src="{% static 'js/midi_player_scripts/inc/jasmid/stream.js'   %}" type="text/javascript"></script>
    <script src="{% static 'js/midi_player_scripts/inc/jasmid/midifile.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/midi_player_scripts/inc/jasmid/replayer.js' %}" type="text/javascript"></script>
    <!-- midi.js midickage -->
    <script src="{% static 'js/midi_player_scripts/audioDetect.js'     %}" type="text/javascript"></script>
    <script src="{% static 'js/midi_player_scripts/gm.js'              %}" type="text/javascript"></script>
    <script src="{% static 'js/midi_player_scripts/loader.js'          %}" type="text/javascript"></script>
    <script src="{% static 'js/midi_player_scripts/plugin.audiotag.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/midi_player_scripts/plugin.webaudio.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/midi_player_scripts/plugin.webmidi.js'  %}" type="text/javascript"></script>
    <script src="{% static 'js/midi_player_scripts/player.js'          %}" type="text/javascript"></script>
    <script src="{% static 'js/midi_player_scripts/synesthesia.js'     %}" type="text/javascript"></script>
    <!-- utils -->
    <script src="{% static 'js/midi_player_scripts/util/dom_request_xhr.js'     %}" type="text/javascript"></script>
    <script src="{% static 'js/midi_player_scripts/util/dom_request_script.js'  %}" type="text/javascript"></script>
    <!-- includes -->
    <script src="{% static 'js/midi_player_scripts/inc/timer.js'      %}" type="text/javascript"></script>
    <script src="{% static 'js/midi_player_scripts/inc/colorspace.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/midi_player_scripts/inc/event.js'      %}" type="text/javascript"></script>
{% endblock %}
    
{% block content %}
    <body>
        
        

        <!-- LOADING OVERLAY -->
        <div class="loading_overlay" id="loading_overlay">
            <div class="loader"></div>
        </div>

        
        </div>
        <!--//////////////////////////////////////////////////////-->         
        <!-- The div where we are going to insert the MIDI Player -->
        <!--//////////////////////////////////////////////////////--> 
        <div class="player_and_buttons">
            <!-- MIDI PLAYER -->
            <div id="player" class="player_div"></div>

        
            <!-- PLAY BUTTON -->
            <button onclick="play_midi()" id="load_midi_and_play" class="button_play_it" type="button" float="left">►</button>
            <!-- PAUSE BUTTON -->
            <button style="display:none" onclick="pause_the_midi()" id="pause_midi" class="button_pause_it" type="button" float="left">&#10074;&#10074;</button>
            <!-- RESUME BUTTON -->
            <button style="display:none" onclick="resume_midi()" id="resume_midi" class="button_play_it" type="button" float="left">►</button>
            <!-- STOP BUTTON -->
            <button style="display:none" onclick="stop_midi()" id="stop_midi" class="button_stop_it" type="button">◼</button>
        </div> 

    
        <!-- CONTROL BUTTONS -->
        <!--div id="button_div" float="right"-->
            <!-- RESET BUTTON -->  
            <!--button id="button_reset" onclick="reset_patterns()" class="button_reset" type="button">RESET</button-->
        <!--/div-->
        
        <!-- The Modal -->

            
        <!-- Warning modal for pattern marking -->
        <div id="overlay_warning" class="modal">
            <!-- Modal content -->
            <div class="modal_content_custom">
                <div class="modal_header_warning_custom">
                    <span class="close_warning modal-close" >&times;</span>
                    <p>Warning</p>
                </div>
                <div class="modal_body_warning_custom">
                    <p><span style="color:crimson">&#9888;</span>&emsp; The end of the pattern cannot be before its start &emsp;<span style="color:crimson">&#9888;</span></p>
                </div>
            </div>
        </div>

        <!-- Warning modal for unfinished pattern  -->
        <div id="submission_warning" class="modal">
            <!-- Modal content -->
            <div class="modal_content_custom">
                <div class="modal_header_warning_custom">
                    <span class="close_warning modal-close" >&times;</span>
                    <p>Warning</p>
                </div>
                <div class="modal_body_warning_custom">
                    <p><span style="color:crimson">&#9888;</span>&emsp;Unfinished patterns are present in your submission &emsp;<span style="color:crimson">&#9888;</span></p>
                </div>
            </div>
        </div>

        <!-- Submission confirmation modal  -->
        <div id="submission_confirmation" class="modal">
            <!-- Modal content -->
            <div class="modal_content_custom">
                <div class="modal-header_custom">
                    <span class="close_warning modal-close" >&times;</span>
                    <p>Submit patterns?</p>
                </div>
                <div class="modal-body_custom" id="modal_confirm_body">
                    <p>Submit the patterns and move to the next task?</p>
                </div>
                <div class="modal_footer_custom">
                    <button type="button" onclick="submit_and_load_next(true)" class="btn btn-default" id="button_submission_confirm">Confirm</button>
                    <button type="button" onclick="submit_and_load_next(false)" class="btn btn-default" id="button_submission_cancel">Cancel</button>
                </div>
            </div>
        </div>

        <!-- Success message, all tasks have been completed  -->
        <div id="modal_the_end" class="modal">
            <!-- Modal content -->
            <div class="modal_content_custom">
                <div class="modal-header_custom">
                    <span class="close_warning modal-close" >&times;</span>
                    <p>Fin</p>
                </div>
                <div class="modal-body_custom" id="modal_confirm_body">
                    <p>Thank you for participating in the experiment! Research results will be published soon.</p>
                </div>
            </div>
        </div>
        <!--//////////////////////////////////////////////--> 
        <!-- The div where we are going to insert the SVG -->
        <!--//////////////////////////////////////////////-->
        
        
        <div align="center" id="svg_output" class="svg_output"></div>

        <div class="div_next_prev" id="button_div" >
            
            <!-- PREVIOUS PAGE BUTTON -->
            <button onclick="prevPage()" id="button_previous_page" class="button_previous_page" type="button" >&#8249;</button>
            <button style="display:none" id="cover_button_previous_page" class="cover_button_previous_page" type="button" >&#8249;</button>
            <!-- NEXT PAGE BUTTON -->
            <button onclick="nextPage()" id="button_next_page" class="button_next_page" type="button" >&#8250;</button>
            <button style="display:none" id="cover_button_next_page" class="cover_button_next_page" type="button" >&#8250;</button>
            
            <!-- NEXT BUTTON -->
            <button onclick="pressed_submit_patterns_button()" id="next" class="button_submit" type="button" float="right">Submit Patterns</button>
            
        </div>
        <div class="div_page_number" id="button_div" >
            
            <!-- PAGE NUMBER BUTTON -->
            <p class="page_number" id="page_number">1/1</p>

            <!-- PAGE NUMBER BUTTON -->
            <p class="task_number" id="task_number">1/1</p>

        </div>
        <script type="text/javascript"> window.CSRF_TOKEN = "{{ csrf_token }}"; </script>
        <!-- Call the script for the midi player -->
        <script src="{% static 'js/main_annotator.js' %}" type="text/javascript"></script>     
        
        <!--script src="{% static 'js/instructions_button.js' %}"  type="text/javascript"></script-->
    </body>
{% endblock %}

pattern_annotator/main/templates/login.html
{% extends "header.html" %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/login_style.css' %}">
{% endblock %}

<body>
    {% include "includes/messages.html" %}
    {% block content %}
        <div id="image_container" class="image_container">
            <div id="bg_image" class="bg_image"></div>
        </div>
        
        <div id="main_login" class="main_login">
            <div id="login" class="login">
                <h2>Login Form</h2>
                <hr/>
                <br>
                <form method="POST">
                    {% csrf_token %}
                    
                    {#%{form.as_p}%#}
                    {% for field in form %}
                        <div class="input-field">
                            {{ field }}
                            <label>{{ field.label }}</label>
                        </div>  
                    {% endfor %}
                    <!--input type="text" name="username" autofocus="" required="" id="id_username" placeholder="Username"-->
  
                          
                        
                    
                    
                    <div class="reg_log_buttons" id="reg_log_buttons">
                    
                        <button class="btn_form" id="submit_form_button" type="submit">Login</button>
                        
                        <hr/>
                        
                        <br/>
                    </div>
                </form>

                <input  type="button" class="switch_button" value="Register" name="register"
                        onclick="location.href='/register'"/>
                
            </div>
        </div>
        
    {% endblock %}
</body>

pattern_annotator/main/templates/register.html
{% extends "header.html" %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/register_style.css' %}">
{% endblock %}

<body>
    {% include "includes/messages.html" %}
    {% block content %}
        <div class="image_container" id="image_container">
            <div id="bg_image" class="bg_image"></div>
        </div>
        
        <div id="main_register" class="main_register">
            <div id="register" class="register">  
                <h2>Registration Form</h2>

                <hr/>
                <br>
                <form method="POST">
                    {% csrf_token %}
                    
                    <div class="sub_entry" id="sub_entry">
                    
                    {% for field in form %}
                        <div class="input-field">
                            {{ field }}
                            <label>{{ field.label }}</label>
                        </div>
                        
                        {% if forloop.counter|divisibleby:"4" %}
                            </div>
                            
                        {% endif %}
                    {%endfor%}
                    
                    <div class="sub_entry" id="sub_entry">
                    {% for field in profile_form %}
                        <div class="input-field">
                            {{ field }}
                            <label>{{ field.label }}</label>
                        </div>
                        {% if forloop.counter|divisibleby:"4" %}
                            </div>
                            {% if forloop.counter != profile_form.fields|length %}
                                <div class="sub_entry" id="sub_entry">
                            {% endif %}
                        {% endif %}
                        
                    {%endfor%}
                    </div>

                    
                    <div class="reg_log_buttons" id="reg_log_buttons">
                        <br>

                        <button class="btn_form" id="submit_form_button" type="submit">Register</button>
                        
                        <hr/>
                        <br/>
                    </div>
                    
                </form>
                
                <input  type="button" class="switch_button" value="Login" name="login"
                        onclick="location.href='/login'"/>
                
                
            
                
            </div>
        </div>
        
        
    {% endblock %}  
</body>